# Written by Yare Brea Espinosa and Pablo Fernández Ríos

import argparse
from collections import namedtuple
import sys


def load_grammar(path: str, stochastic_file: bool) -> tuple[list[str], dict[str, float]]:
    """Load the .txt file holding the grammar, skipping blank lines"""

    if not path.endswith(".txt"):
        raise ValueError("Error: make sure the grammar file has the .txt extension")

    rules = []
    seen_rules = set()
    probabilities = {}       # Rule as a string -> its probability, when there is one
    probabilities_by_head = {}  # Used to check the probabilities are distributed correctly
    try:
        with open(file=path, mode="r", encoding="utf-8") as f:
            for line in f:
                line = line.strip().split()

                if not line:
                    continue

                # Check the rules are well formed
                if stochastic_file and (len(line) != 2 or not line[0].isalpha()):
                    raise ValueError(f"Format error in: '{' '.join(line)}': the entry must be a run of letters (the rule) and a number (the probability), separated by a space.")
                elif not stochastic_file and (len(line) != 1 or not line[0].isalpha()):
                    raise ValueError(f"Format error in: '{' '.join(line)}': the entry must be a run of contiguous letters")

                rule = line[0]

                # DUPLICATE RULE CHECK
                if rule in seen_rules:
                    print(f"Warning: rule '{rule}' is duplicated. Ignoring the repeat. For rules with probabilities only the first occurrence survives.", file=sys.stderr)
                    continue  # Skip this line and move on to the next
                rules.append(rule)
                seen_rules.add(rule)

                if stochastic_file:
                    try:
                        prob = float(line[1])
                    except ValueError:
                        raise ValueError(f"Format error in '{' '.join(line)}': the probability must be numeric (use a dot for the decimal point)")
                    if not (0 <= prob <= 1):
                        raise ValueError(f"Value error in '{' '.join(line)}': the probability is outside the interval [0, 1]")

                    probabilities[line[0]] = prob
                    probabilities_by_head.setdefault(line[0][0], []).append(prob)

    except FileNotFoundError:
        raise FileNotFoundError(f"Error: the file '{path}' does not exist in this directory.")

    if not rules:
        raise ValueError("Error: the file is empty or holds no valid rules.")

    # Check whether some probabilities go over one (an error) or fall short of it (a warning)
    for symbol in probabilities_by_head:
        total = sum(probabilities_by_head[symbol])
        if total > 1 + 1e-9:  # Guard against imprecise floating point sums
            raise ValueError(f"Error: the probabilities of the rules headed by {symbol} add up to more than one.")
        elif total < 1 - 1e-9:
            print(f"Warning: the probabilities of the rules headed by {symbol} do not reach one. Some production rules may be missing.", file=sys.stderr)

    return rules, probabilities


class CFG:
    """Representation of a context-free grammar."""

    def __init__(self, rules: list[str]):
        self.rules = self._index_rules(rules)
        self.axiom = rules[0][0]  # First character of the first rule = start symbol

    def _index_rules(self, rules: list[str]):
        """
        From the data read out of the text file, build the dictionary that stores
        the production rules:

        - rules_by_body, keyed by the set of symbols appearing as the body of some
        rule, with the heads of the rules they appear in as the value. For instance,
        the rule SAB is stored as {'AB': {'S'}}.

        Indexing by body rather than by head is what makes CYK cheap: the inner loop
        asks "which non-terminals produce this pair of symbols?", which is a single
        dictionary lookup instead of a scan over every rule.
        """
        rules_by_body = {}

        for rule in rules:
            head, body = rule[0], rule[1:]

            # The same body can be generated by several non-terminals
            rules_by_body.setdefault(body, set()).add(head)

        return rules_by_body


def is_cnf(rules: list[str]) -> bool:
    """Check that every rule of the grammar is in Chomsky Normal Form"""
    for rule in rules:

        # Rule ABC: head + two non-terminals. For instance, "SAB"
        if len(rule) == 3 and rule.isupper():
            continue

        # Rule Aa: uppercase head + lowercase terminal. For instance, "Sa"
        if len(rule) == 2 and rule[0].isupper() and rule[1].islower():
            continue

        return False

    return True


# Named tuple holding each entry of the trace (the table used to rebuild the trees)
TableEntry = namedtuple("TableEntry", ["body", "left_cell", "right_cell", "prob"])


def build_trees(table: list[list[dict[str, list[TableEntry]]]], symbol: str, i: int, j: int) -> list[tuple[str, float]]:
    """Build every derivation tree for a rule out of table, which holds all the generating rules"""

    trees = []

    for body, left_cell, right_cell, prob in table[i][j][symbol]:

        # When running as a stochastic parser we keep the probability attached to
        # the rule; otherwise we keep 1
        rule_prob = prob if prob is not None else 1.0

        if left_cell is None:  # Terminal symbol
            trees.append((f"({symbol} {body})", rule_prob))

        else:
            # Iterate over every possible tree for the left and right child
            # (an ambiguous grammar can give more than one of each)
            for right_tree, right_prob in build_trees(table, body[1], *right_cell):
                for left_tree, left_prob in build_trees(table, body[0], *left_cell):

                    # Combine each pair of subtrees, multiplying their probabilities with the current rule's
                    trees.append((f"({symbol} {left_tree} {right_tree})", rule_prob * left_prob * right_prob))

    return trees


def cyk_parse(cfg: CFG, sentence: str, pwt: bool, probabilities: dict[str, float]) -> bool:
    """Run the CYK algorithm to decide whether a string belongs to the grammar"""

    n = len(sentence)
    rules_by_body = cfg.rules

    # Lower-triangular table of dictionaries, used for both stochastic and categorical parsing.
    #
    # It is indexed table[i][j], where i is the position the substring STARTS at and j is its
    # length minus one -- so table[i][j] describes sentence[i : i+j+1]. Only i + j < n is
    # meaningful, which is why row i is allocated with exactly n - i cells: the comprehension
    # counts i down from n to 1, giving rows of length n, n-1, ... 1. Storing it this way
    # rather than as a full n x n square keeps the two loops below free of bounds checks.
    table = [[{} for _ in range(i)] for i in range(n, 0, -1)]

    _fill_base(table, rules_by_body, n, sentence, probabilities)
    _fill_table(table, rules_by_body, n, probabilities)

    # The string is accepted if the axiom sits at the apex of the triangular table
    accepted = cfg.axiom in table[0][n - 1]

    # Only print the tree when the string is in the language
    if accepted:
        stochastic = bool(probabilities)

        # With -t (parsing with trees) or -s (stochastic parsing) we print the tree
        if pwt or stochastic:
            trees = build_trees(table, cfg.axiom, 0, n - 1)

            for tree in trees:
                if stochastic:
                    prob = int(tree[1] * 100000) / 100000  # Truncate to 5 decimals, as the assignment does
                    print(f"{tree[0]} {prob:.5f}")
                else:
                    print(tree[0])
            print()

    return accepted


def _fill_base(table: list[list[dict[str, list[TableEntry]]]], rules_by_body: dict[str, set[str]], n: int, sentence: str, probabilities: dict[str, float]):
    """Fill the base row of the table used by the CYK algorithm"""

    for i in range(n):
        # Find which non-terminals produce sentence[i]. If there are none, return []
        heads = rules_by_body.get(sentence[i], [])

        for head in heads:
            key = head + sentence[i]  # Rebuild the rule, which acts as the key
            # Without the -s option we simply store None
            prob = probabilities[key] if probabilities else None

            # Record in the current cell the terminals generated by this head
            table[i][0][head] = [TableEntry(sentence[i], None, None, prob)]


def _fill_table(table: list[list[dict[str, list[TableEntry]]]], rules_by_body: dict[str, set[str]], n: int, probabilities: dict[str, float]):
    """Fill every row of the CYK table except the base"""

    for j in range(1, n):      # rows: substring length minus one
        for i in range(n - j):  # columns: starting position

            # Try every way of splitting the substring into two halves
            for k in range(j):
                left_keys = table[i][k].keys()
                right_keys = table[i + k + 1][j - k - 1].keys()

                # Take the cartesian product of both cells
                for symbol_a in left_keys:
                    for symbol_b in right_keys:
                        combination = symbol_a + symbol_b
                        heads = rules_by_body.get(combination, [])

                        # Store the trace saying how this non-terminal can be generated
                        for head in heads:
                            key = head + symbol_a + symbol_b
                            prob = probabilities[key] if probabilities else None

                            # Store the tuple that lets us rebuild the tree
                            entry = TableEntry(combination, (i, k), (i + k + 1, j - k - 1), prob)
                            # If the key is absent it is created; otherwise the new entry is added
                            # at the FRONT. Prepending is what makes the derivation trees come out in
                            # the order the assignment expects: split points k are visited in
                            # increasing order, and inserting at 0 reverses that, so build_trees
                            # emits the widest left child first. Appending here silently swaps the
                            # order of the two trees printed for 'bbab'.
                            table[i][j].setdefault(head, []).insert(0, entry)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("file", help=".txt file holding the grammar")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("-g", action="store_true", help="Check the grammar is in Chomsky Normal Form")
    group.add_argument("-p", action="store_true", help="Run the CYK algorithm")
    group.add_argument("-t", action="store_true", help="Show every derivation tree")
    group.add_argument("-s", action="store_true", help="Stochastic parsing: show the trees with their probabilities")

    args = parser.parse_args()

    try:
        # Load the rules, and the probabilities if they were supplied; otherwise an empty dict
        rules, probabilities = load_grammar(args.file, args.s)

        # -g mode, for CNF validation
        if args.g:
            print("yes") if is_cnf(rules) else print("no")

        # -p/-t/-s modes, for recognising strings
        else:
            if not is_cnf(rules):
                print("Error: the grammar is not in Chomsky Normal Form.")
            else:
                grammar = CFG(rules)
                # Read line by line from stdin. EOFError marks the end of the input
                while True:
                    try:
                        sentence = input().strip()
                        if not sentence:  # Skip blank lines
                            continue
                        if not sentence.isalpha() or not sentence.islower():
                            print(f"Error: the string '{sentence}' does not consist only of contiguous terminal symbols (lowercase).")
                            continue
                        if cyk_parse(grammar, sentence, args.t, probabilities):
                            if not args.t and not args.s:
                                print("yes")
                        else:
                            print("no")
                            if args.t or args.s:
                                print()  # Leave the separating blank line the assignment asks for

                    except EOFError:
                        break

    except Exception as e:
        print(e, file=sys.stderr)  # Send errors to stderr so normal stdout stays clean
